<?php
$rareradio_slider_sc = rareradio_get_theme_option( 'front_page_title_shortcode' );
if ( ! empty( $rareradio_slider_sc ) && strpos( $rareradio_slider_sc, '[' ) !== false && strpos( $rareradio_slider_sc, ']' ) !== false ) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider
		<?php
		if ( rareradio_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
	">
	<?php
		// Add anchor
		$rareradio_anchor_icon = rareradio_get_theme_option( 'front_page_title_anchor_icon' );
		$rareradio_anchor_text = rareradio_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $rareradio_anchor_icon ) || ! empty( $rareradio_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $rareradio_anchor_icon ) ? ' icon="' . esc_attr( $rareradio_anchor_icon ) . '"' : '' )
									. ( ! empty( $rareradio_anchor_text ) ? ' title="' . esc_attr( $rareradio_anchor_text ) . '"' : '' )
									. ']'
		);
	}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode( $rareradio_slider_sc );
	?>
	</div>
	<?php

} else {

	?>
	<div class="front_page_section front_page_section_title
		<?php
		$rareradio_scheme = rareradio_get_theme_option( 'front_page_title_scheme' );
		if ( ! empty( $rareradio_scheme ) && ! rareradio_is_inherit( $rareradio_scheme ) ) {
			echo ' scheme_' . esc_attr( $rareradio_scheme );
		}
		echo ' front_page_section_paddings_' . esc_attr( rareradio_get_theme_option( 'front_page_title_paddings' ) );
		if ( rareradio_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
		"
		<?php
		$rareradio_css      = '';
		$rareradio_bg_image = rareradio_get_theme_option( 'front_page_title_bg_image' );
		if ( ! empty( $rareradio_bg_image ) ) {
			$rareradio_css .= 'background-image: url(' . esc_url( rareradio_get_attachment_url( $rareradio_bg_image ) ) . ');';
		}
		if ( ! empty( $rareradio_css ) ) {
			echo ' style="' . esc_attr( $rareradio_css ) . '"';
		}
		?>
	>
	<?php
		// Add anchor
		$rareradio_anchor_icon = rareradio_get_theme_option( 'front_page_title_anchor_icon' );
		$rareradio_anchor_text = rareradio_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $rareradio_anchor_icon ) || ! empty( $rareradio_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $rareradio_anchor_icon ) ? ' icon="' . esc_attr( $rareradio_anchor_icon ) . '"' : '' )
									. ( ! empty( $rareradio_anchor_text ) ? ' title="' . esc_attr( $rareradio_anchor_text ) . '"' : '' )
									. ']'
		);
	}
	?>
		<div class="front_page_section_inner front_page_section_title_inner
		<?php
		if ( rareradio_get_theme_option( 'front_page_title_fullheight' ) ) {
			echo ' rareradio-full-height sc_layouts_flex sc_layouts_columns_middle';
		}
		?>
			"
			<?php
			$rareradio_css      = '';
			$rareradio_bg_mask  = rareradio_get_theme_option( 'front_page_title_bg_mask' );
			$rareradio_bg_color_type = rareradio_get_theme_option( 'front_page_title_bg_color_type' );
			if ( 'custom' == $rareradio_bg_color_type ) {
				$rareradio_bg_color = rareradio_get_theme_option( 'front_page_title_bg_color' );
			} elseif ( 'scheme_bg_color' == $rareradio_bg_color_type ) {
				$rareradio_bg_color = rareradio_get_scheme_color( 'bg_color', $rareradio_scheme );
			} else {
				$rareradio_bg_color = '';
			}
			if ( ! empty( $rareradio_bg_color ) && $rareradio_bg_mask > 0 ) {
				$rareradio_css .= 'background-color: ' . esc_attr(
					1 == $rareradio_bg_mask ? $rareradio_bg_color : rareradio_hex2rgba( $rareradio_bg_color, $rareradio_bg_mask )
				) . ';';
			}
			if ( ! empty( $rareradio_css ) ) {
				echo ' style="' . esc_attr( $rareradio_css ) . '"';
			}
			?>
		>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$rareradio_caption = rareradio_get_theme_option( 'front_page_title_caption' );
				if ( ! empty( $rareradio_caption ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo ! empty( $rareradio_caption ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( $rareradio_caption, 'rareradio_kses_content' ); ?></h1>
					<?php
				}

				// Description (text)
				$rareradio_description = rareradio_get_theme_option( 'front_page_title_description' );
				if ( ! empty( $rareradio_description ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo ! empty( $rareradio_description ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( wpautop( $rareradio_description ), 'rareradio_kses_content' ); ?></div>
					<?php
				}

				// Buttons
				if ( rareradio_get_theme_option( 'front_page_title_button1_link' ) != '' || rareradio_get_theme_option( 'front_page_title_button2_link' ) != '' ) {
					?>
					<div class="front_page_section_buttons front_page_section_title_buttons">
					<?php
						rareradio_show_layout( rareradio_customizer_partial_refresh_front_page_title_button1_link() );
						rareradio_show_layout( rareradio_customizer_partial_refresh_front_page_title_button2_link() );
					?>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}
